<p>To flip through the page images one by one:</p>

<ul>
<li>Click a filename from the list to set the keyboard "focus"</li>
<li>Next image: press the <b>down-arrow</b> key</li>
<li>Previous image: press the <b>up-arrow</b> key</li>
</ul>

<p>To jump to a particular image:</p>

<ul>
<li>Scroll through the list and click any image</li>
</ul>

<p>or</p>

<ul>
<li>Enter a page image number in the textbox</li>
<li>Click <b>Jump</b> (or hit Enter)</li>
</ul>

<p>If the page image number has leading zeroes, you don't have to
enter them (so entering 8 jumps to image _008).</p>

<p>To select a different book to view, click <b>Select New ID</b>.</p>

<p>To start over (so you can choose between <b>View text and
images</b> and <b>View images only</b>) click <b>Proofreader
Home</b>.</p>

<p>The frames are adjustable. (To adjust a frame, hover the pointer
over the frame border; when the pointer changes to a double arrow,
click and drag.)</p>

<p><b>NOTE:</b> Proofreader uses JavaScript. If Proofreader does not
seem to be working at all, check your web browser's settings and make
sure JavaScript is enabled.</p>
